port: "8080"

db:
  username: "postgres"
  host: "localhost"
  port: "5432"
  database: "postgres"
  sslmode: "disable"

redis:
  addr: "localhost:5433"
  db: 0

oauth:
  baseURL: "http://localhost:8080"
  google:
    redirectURL: "http://localhost:8080/auth/oauth/google/callback"
    scopes:
      - "https://www.googleapis.com/auth/userinfo.email"
      - "https://www.googleapis.com/auth/userinfo.profile"
  github:
    redirectURL: "http://localhost:8080/auth/oauth/github/callback"
    scopes:
      - "user:email"
      - "read:user"