# .github/workflows/ci-cd-main.yml
name: Nuxt CD (Main)

on:
  push:
    branches: [main]
    paths:
      - 'Nuxt4/**'
      - '.github/workflows/nuxt-ci-cd-main.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # CI Шаги (аналогично ci-dev.yml)
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        working-directory: ./Nuxt4
        run: bun install --frozen-lockfile

      - name: Lint code
        working-directory: ./Nuxt4
        run: bun run lint

      - name: Build project
        working-directory: ./Nuxt4
        run: bun run build

      # CD Шаги (Docker)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        # Необходим для сборки образов под разные архитектуры, если потребуется

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        # Настраивает BuildKit для улучшенной сборки

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }} # Это твой логин на GitHub
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        if: github.event_name == 'push'
        uses: docker/build-push-action@v6
        with:
          context: ./Nuxt4
          file: ./Nuxt4/Dockerfile
          push: true
          tags: |
            ghcr.io/artemchadaev/nuxt:latest
            ghcr.io/artemchadaev/nuxt:${{ github.sha }}
