# .github/workflows/ci-dev.yml
name: Nuxt CI (Dev)

on:
  push:
    branches: [dev]
    paths:
      - 'Nuxt4/**'
      - '.github/workflows/nuxt-ci-dev.yml'
  pull_request:
    branches: [dev]
    paths:
      - 'Nuxt4/**'
      - '.github/workflows/nuxt-ci-dev.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Используем oven-sh/setup-bun для установки Bun
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest # Или укажите конкретную версию Bun

      - name: Install dependencies
        working-directory: ./Nuxt4
        run: bun install --frozen-lockfile

      - name: Lint code
        working-directory: ./Nuxt4
        run: bun run lint

      - name: Build project
        working-directory: ./Nuxt4
        run: bun run build
